In [1]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("./iris/iris.csv")
statistical_analysis = df.describe()
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [2]:
iris_setosa = df[df['Species'] == 'Iris-setosa'].drop(columns=['Species'])
iris_versicolor = df[df['Species'] == 'Iris-versicolor'].drop(columns=['Species'])
iris_virginica = df[df['Species'] == 'Iris-virginica'].drop(columns=['Species'])

In [3]:
lr_df = iris_setosa.drop(columns=["Id", "PetalLengthCm", "PetalWidthCm"])
lr_df.rename(
    columns={"SepalLengthCm": "sepal_length", "SepalWidthCm": "sepal_width", 'Id': 'id'},
    inplace=True,
)

training_df = lr_df[lr_df.index < lr_df.shape[0] * 0.8].reset_index(drop=True)
test_df = lr_df[lr_df.index >= lr_df.shape[0] * 0.8].reset_index(drop=True)

In [4]:
# x = sepal_length, y = sepal_width
sepal_length_mean = training_df["sepal_length"].mean()
sepal_width_mean = training_df["sepal_width"].mean()

slope = (
    (
        (training_df["sepal_length"] - sepal_length_mean)
        * (training_df["sepal_width"] - sepal_width_mean)
    )
).sum() / (((training_df["sepal_length"] - sepal_length_mean) ** 2)).sum()

constant = sepal_width_mean - slope * sepal_length_mean

In [5]:
pred_df = (slope * test_df['sepal_length'] + constant).round(1)
final_pred_df = pd.concat([pred_df, test_df["sepal_width"]], axis=1)
final_pred_df

   sepal_length  sepal_width
0           3.4          3.5
1           3.0          2.3
2           3.0          3.2
3           3.4          3.5
4           3.5          3.8
5           3.3          3.0
6           3.5          3.8
7           3.1          3.2
8           3.6          3.7
9           3.4          3.3