In [97]:
import math
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv("./iris/iris.csv")
statistical_analysis = df.describe()
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [98]:
df.replace({"Species": {"Iris-setosa": 0, "Iris-versicolor": 1, "Iris-virginica": 2}}, inplace=True)
df.rename(
    columns={
        "PetalLengthCm": "petal_length",
        "PetalWidthCm": "petal_width",
        "SepalLengthCm": "sepal_length",
        "SepalWidthCm": "sepal_width",
        "Species": "species",
        "Id": "id",
    },
    inplace=True,
)
df.drop(columns=["id"], inplace=True)
iris_setosa = df[df['species'] == 0].drop(columns=['species'])
iris_versicolor = df[df['species'] == 1].drop(columns=['species'])
iris_virginica = df[df['species'] == 2].drop(columns=['species'])

# Linear Regression

In [99]:
x = iris_setosa[['petal_length']]
y = iris_setosa["petal_width"]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=30)

In [100]:
model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

pd.concat([y_test, pd.Series(y_pred.round(1), index=y_test.index)], axis=1)

    petal_width    0
41          0.3  0.2
20          0.2  0.3
32          0.1  0.3
43          0.6  0.3
10          0.2  0.3
29          0.2  0.3
33          0.2  0.2
25          0.2  0.3
34          0.1  0.3
19          0.3  0.3

In [101]:
# Evaluate
print("R²:           ", r2_score(y_test, y_pred))
print("RMSE:         ", mean_squared_error(y_test, y_pred) ** 0.5)
print("Coefficients: ", model.coef_)    # one weight per feature
print("Intercept:    ", model.intercept_)

R²:            -0.019979001976284216
RMSE:          0.13699494018526243
Coefficients:  [0.20454545]
Intercept:     -0.051590909090909104

# Multivariate Regression

In [102]:
x = df.drop(columns=["species"])
y = df["species"]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=30)

In [103]:
model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

pd.concat([y_test, pd.Series(y_pred.astype(int), index=y_test.index)], axis=1)

    species  0
20        0  0
5         0  0
3         0  0
101       2  1
82        1  1
80        1  1
123       2  1
145       2  1
74        1  1
107       2  1
38        0  0
103       2  1
93        1  0
99        1  1
8         0  0
97        1  1
32        0  0
1         0  0
24        0  0
72        1  1
133       2  1
42        0  0
0         0  0
35        0  0
105       2  1
132       2  1
70        1  1
136       2  2
2         0  0
87        1  1

In [104]:
# Evaluate
print("R²:           ", r2_score(y_test, y_pred))
print("RMSE:         ", mean_squared_error(y_test, y_pred) ** 0.5)
print("Coefficients: ", model.coef_)    # one weight per feature
print("Intercept:    ", model.intercept_)

R²:            0.9338744481641292
RMSE:          0.2136039109350549
Coefficients:  [-0.10613545 -0.05145188  0.21136685  0.64090896]
Intercept:     0.21103100324921675